import fetch from "node-fetch";

async function run() {
  const payload = {
    jsonrpc: "2.0",
    id: 1,
    method: "simulateTransaction",
    params: {
      transaction: "AAAAAQAAAAC4ZInD2eI1z2x3aUfK0QZzUjV4s4Y9s/sA868d4kGn6QAAAGQAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAABwQ1B5YbWP7b4BCLNpKMi9Eku0zPohD2Gy+M0hpR0LgAAAAEAAAAAAAAABAAAAA8AAAAHZGVwb3NpdAAAAAAGAAAAEgAAAAEAAAAAuGSJw9niNc9sd2lHytEGc1I1eLOGPbP7APOvHeJBp+kAAAASAAAAAQAAAAB3S+9dD1R/VwzN3tG6O1i6j27t0U6Q/s/A1R4X1w01mQAAAA0AAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEgAAAAHXkotywnA8z+r365/0701QSlWouXn8m0UOoshCtNHOYQAAAAoAAAAAAAAAAAAAAAAAmJaA"
    }
  };
  // This is a dummy transaction I'll replace.
}
run();
